In [4]:
import os
import pandas as pd

data_dir = 'data'

In [17]:
df = pd.read_csv(os.path.join(data_dir, 'ADNIMERGE_19Jun2025.csv'), low_memory=False)


https://adni.bitbucket.io/reference/adnimerge.html#examples

https://adni.loni.usc.edu/wp-content/uploads/2012/08/slide_data_training_part2_reduced-size.pdf

In [22]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16421 entries, 0 to 16420
Data columns (total 116 columns):
 #    Column                    Dtype
---   ------                    -----
 0    RID                       int64
 1    COLPROT                   object
 2    ORIGPROT                  object
 3    PTID                      object
 4    SITE                      int64
 5    VISCODE                   object
 6    EXAMDATE                  object
 7    DX_bl                     object
 8    AGE                       float64
 9    PTGENDER                  object
 10   PTEDUCAT                  int64
 11   PTETHCAT                  object
 12   PTRACCAT                  object
 13   PTMARRY                   object
 14   APOE4                     float64
 15   FDG                       float64
 16   PIB                       float64
 17   AV45                      float64
 18   FBB                       float64
 19   ABETA                     object
 20   TAU                       object
 21   PTAU                      object
 22   CDRSB                     float64
 23   ADAS11                    float64
 24   ADAS13                    float64
 25   ADASQ4                    float64
 26   MMSE                      float64
 27   RAVLT_immediate           float64
 28   RAVLT_learning            float64
 29   RAVLT_forgetting          float64
 30   RAVLT_perc_forgetting     float64
 31   LDELTOTAL                 float64
 32   DIGITSCOR                 float64
 33   TRABSCOR                  float64
 34   FAQ                       float64
 35   MOCA                      float64
 36   EcogPtMem                 float64
 37   EcogPtLang                float64
 38   EcogPtVisspat             float64
 39   EcogPtPlan                float64
 40   EcogPtOrgan               float64
 41   EcogPtDivatt              float64
 42   EcogPtTotal               float64
 43   EcogSPMem                 float64
 44   EcogSPLang                float64
 45   EcogSPVisspat             float64
 46   EcogSPPlan                float64
 47   EcogSPOrgan               float64
 48   EcogSPDivatt              float64
 49   EcogSPTotal               float64
 50   FLDSTRENG                 object
 51   FSVERSION                 object
 52   IMAGEUID                  float64
 53   Ventricles                float64
 54   Hippocampus               float64
 55   WholeBrain                float64
 56   Entorhinal                float64
 57   Fusiform                  float64
 58   MidTemp                   float64
 59   ICV                       float64
 60   DX                        object
 61   mPACCdigit                float64
 62   mPACCtrailsB              float64
 63   EXAMDATE_bl               object
 64   CDRSB_bl                  float64
 65   ADAS11_bl                 float64
 66   ADAS13_bl                 float64
 67   ADASQ4_bl                 float64
 68   MMSE_bl                   float64
 69   RAVLT_immediate_bl        float64
 70   RAVLT_learning_bl         float64
 71   RAVLT_forgetting_bl       float64
 72   RAVLT_perc_forgetting_bl  float64
 73   LDELTOTAL_BL              float64
 74   DIGITSCOR_bl              float64
 75   TRABSCOR_bl               float64
 76   FAQ_bl                    float64
 77   mPACCdigit_bl             float64
 78   mPACCtrailsB_bl           float64
 79   FLDSTRENG_bl              object
 80   FSVERSION_bl              object
 81   IMAGEUID_bl               float64
 82   Ventricles_bl             float64
 83   Hippocampus_bl            float64
 84   WholeBrain_bl             float64
 85   Entorhinal_bl             float64
 86   Fusiform_bl               float64
 87   MidTemp_bl                float64
 88   ICV_bl                    float64
 89   MOCA_bl                   float64
 90   EcogPtMem_bl              float64
 91   EcogPtLang_bl             float64
 92   EcogPtVisspat_bl          float64
 93   EcogPtPlan_bl             float64
 94   EcogPtOrgan_bl            float64
 95   EcogPtDivatt_bl           float64
 96   EcogPtTotal_bl            float64
 97   EcogSPMem_bl              float64
 98   EcogSPLang_bl             float64
 99   EcogSPVisspat_bl          float64
 100  EcogSPPlan_bl             float64
 101  EcogSPOrgan_bl            float64
 102  EcogSPDivatt_bl           float64
 103  EcogSPTotal_bl            float64
 104  ABETA_bl                  object
 105  TAU_bl                    object
 106  PTAU_bl                   object
 107  FDG_bl                    float64
 108  PIB_bl                    float64
 109  AV45_bl                   float64
 110  FBB_bl                    float64
 111  Years_bl                  float64
 112  Month_bl                  float64
 113  Month                     int64
 114  M                         int64
 115  update_stamp              object
dtypes: float64(88), int64(5), object(23)
memory usage: 14.5+ MB

In [20]:
df.describe()

,RID,SITE,AGE,PTEDUCAT,APOE4,FDG,PIB,AV45,FBB,CDRSB,...,EcogSPDivatt_bl,EcogSPTotal_bl,FDG_bl,PIB_bl,AV45_bl,FBB_bl,Years_bl,Month_bl,Month,M
count,16421.000000,16421.000000,16412.000000,16421.000000,16056.000000,3693.000000,223.000000,3080.000000,513.000000,11747.000000,...,8915.000000,9085.000000,11220.000000,154.000000,7836.000000,1099.000000,16421.000000,16421.000000,16421.000000,16421.000000
mean,2899.082273,81.733329,73.214173,16.105779,0.516193,1.175624,1.783161,1.193030,1.175212,2.047927,...,1.735025,1.601863,1.226786,1.582256,1.186525,1.163109,2.738280,32.792027,32.712259,32.580903
std,2220.442824,132.762777,7.028099,2.762672,0.646953,0.167288,0.422511,0.230866,0.246133,2.866563,...,0.861453,0.670951,0.153364,0.302114,0.220110,0.236850,2.939675,35.203809,35.193789,35.124178
min,2.000000,2.000000,50.400000,4.000000,0.000000,0.566989,1.095000,0.809000,0.870200,0.000000,...,1.000000,1.000000,0.621933,1.155000,0.810000,0.870200,0.000000,0.000000,0.000000,0.000000
25%,751.000000,22.000000,68.500000,14.000000,0.000000,1.071700,1.361250,1.010075,0.996900,0.000000,...,1.000000,1.102560,1.134820,1.360000,1.012400,0.995100,0.506502,6.065570,6.000000,6.000000
50%,2308.000000,41.000000,73.200000,16.000000,0.000000,1.180590,1.850000,1.106800,1.054000,1.000000,...,1.500000,1.333330,1.234580,1.490000,1.098400,1.041700,1.960300,23.475400,24.000000,24.000000
75%,4707.000000,123.000000,78.100000,18.000000,1.000000,1.287080,2.127500,1.358425,1.350800,3.000000,...,2.000000,1.897440,1.331470,1.835000,1.346900,1.318600,4.010950,48.032800,48.000000,48.000000
max,7125.000000,941.000000,91.400000,20.000000,2.000000,1.776170,2.927500,2.686600,2.008800,18.000000,...,4.000000,3.948720,1.776170,2.282500,2.010100,1.909000,16.961000,203.115000,204.000000,204.000000

In [18]:
df.head()

,RID,COLPROT,ORIGPROT,PTID,SITE,VISCODE,EXAMDATE,DX_bl,AGE,PTGENDER,...,PTAU_bl,FDG_bl,PIB_bl,AV45_bl,FBB_bl,Years_bl,Month_bl,Month,M,update_stamp
0,2,ADNI1,ADNI1,011_S_0002,11,bl,2005-09-08,CN,74.3,Male,...,NaN,1.33615,NaN,NaN,NaN,0.000000,0.00000,0,0,2023-07-07 04:59:40.0
1,3,ADNI1,ADNI1,011_S_0003,11,bl,2005-09-12,AD,81.3,Male,...,22.83,1.10860,NaN,NaN,NaN,0.000000,0.00000,0,0,2023-07-07 04:59:40.0
2,3,ADNI1,ADNI1,011_S_0003,11,m06,2006-03-13,AD,81.3,Male,...,22.83,1.10860,NaN,NaN,NaN,0.498289,5.96721,6,6,2023-07-07 04:59:40.0
3,3,ADNI1,ADNI1,011_S_0003,11,m12,2006-09-12,AD,81.3,Male,...,22.83,1.10860,NaN,NaN,NaN,0.999316,11.96720,12,12,2023-07-07 04:59:40.0
4,3,ADNI1,ADNI1,011_S_0003,11,m24,2007-09-12,AD,81.3,Male,...,22.83,1.10860,NaN,NaN,NaN,1.998630,23.93440,24,24,2023-07-07 04:59:40.0

In [ ]:
csf_cols = ['ABETA', 'TAU', 'PTAU', 'ABETA_bl', 'TAU_bl', 'PTAU_bl']

In [ ]:
huw_cols = ['PTGENDER', 'PTEDUCAT', 'AGE', 'DX', 'DX_bl', 'MMSE_bl', 'EcogPtTotal_bl', 'LDELTOTAL_BL', 'mPACCdigit_bl', 'mPACCtrailsB_bl', 'RAVLT_immediate_bl', 'RAVLT_learning_bl', 'RAVLT_forgetting_bl', 'RAVLT_perc_forgetting_bl']

In [32]:
parent_questionnaire_df = pd.read_csv(os.path.join(data_dir, 'FAMHXPAR_19Jun2025.csv'), low_memory=False)

In [33]:
parent_questionnaire_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10486 entries, 0 to 10485
Data columns (total 219 columns):
 #    Column                          Dtype
---   ------                          -----
 0    RMT_PHASE                       object
 1    ADNIOnlineID                    object
 2    PTID                            object
 3    RMT_Timepoint                   object
 4    EXAMDATE                        object
 5    SCREENER_SCORE                  int64
 6    SCREENER_RECOMMEND              int64
 7    QC_ATTEMPTS                     int64
 8    QC_PASSED                       int64
 9    USER_AGENT                      object
 10   STORY1IMM_LANGUAGE              object
 11   STORY1IMM_PLAYBACK_COUNT        float64
 12   STORY1IMM_AUDIO_LENGTH          float64
 13   STORY1IMM_NUM_PRONOUNS          float64
 14   STORY1IMM_NUM_NOUNS             float64
 15   STORY1IMM_NUM_PROPER_NOUNS      float64
 16   STORY1IMM_NUM_VERBS             float64
 17   STORY1IMM_NUM_ADVERBS           float64
 18   STORY1IMM_NUM_ADJECTIVES        float64
 19   STORY1IMM_NUM_WORDS             float64
 20   STORY1IMM_IDEA_DENSITY          float64
 21   STORY1IMM_UNIQUE_WORDS_RATIO    float64
 22   STORY1IMM_MEAN_LETTER_PER_WORD  float64
 23   STORY1IMM_GMATCH                float64
 24   STORY1IMM_SPEECH_DURATION       float64
 25   STORY1IMM_NONSPEECH_PROPORTION  float64
 26   STORY1IMM_SPEECH_RATE           float64
 27   STORY1IMM_ARTICULATION_RATE     float64
 28   STORY1IMM_NUM_PAUSES            float64
 29   STORY1IMM_MEAN_PAUSE_LENGTH     float64
 30   STORY1IMM_AMPLITUDE_SD          float64
 31   STORY1IMM_F0_MEAN               float64
 32   STORY1IMM_F0_SD                 float64
 33   STORY1IMM_INTENSITY_MEAN        float64
 34   STORY1IMM_INTENSITY_SD          float64
 35   STORY1IMM_MFCC_1_MEAN           float64
 36   STORY1IMM_MFCC_2_MEAN           float64
 37   STORY1IMM_MFCC_3_MEAN           float64
 38   STORY1IMM_MFCC_4_MEAN           float64
 39   STORY1IMM_MFCC_5_MEAN           float64
 40   STORY1IMM_MFCC_6_MEAN           float64
 41   STORY1IMM_MFCC_7_MEAN           float64
 42   STORY1IMM_MFCC_8_MEAN           float64
 43   STORY1IMM_MFCC_9_MEAN           float64
 44   STORY1IMM_MFCC_10_MEAN          float64
 45   STORY1IMM_MFCC_11_MEAN          float64
 46   STORY1IMM_MFCC_12_MEAN          float64
 47   STORY1IMM_MFCC_13_MEAN          float64
 48   STORY1IMM_MFCC_1_SD             float64
 49   STORY1IMM_MFCC_2_SD             float64
 50   STORY1IMM_MFCC_3_SD             float64
 51   STORY1IMM_MFCC_4_SD             float64
 52   STORY1IMM_MFCC_5_SD             float64
 53   STORY1IMM_MFCC_6_SD             float64
 54   STORY1IMM_MFCC_7_SD             float64
 55   STORY1IMM_MFCC_8_SD             float64
 56   STORY1IMM_MFCC_9_SD             float64
 57   STORY1IMM_MFCC_10_SD            float64
 58   STORY1IMM_MFCC_11_SD            float64
 59   STORY1IMM_MFCC_12_SD            float64
 60   STORY1IMM_MFCC_13_SD            float64
 61   STORY1IMM_FORMANTS_1_MEAN       float64
 62   STORY1IMM_FORMANTS_2_MEAN       float64
 63   STORY1IMM_FORMANTS_3_MEAN       float64
 64   STORY1IMM_FORMANTS_4_MEAN       float64
 65   STORY1IMM_FORMANTS_1_SD         float64
 66   STORY1IMM_FORMANTS_2_SD         float64
 67   STORY1IMM_FORMANTS_3_SD         float64
 68   STORY1IMM_FORMANTS_4_SD         float64
 69   STORY1IMM_LOCAL_JITTER          float64
 70   STORY1IMM_LOCAL_ABS_JITTER      float64
 71   STORY1IMM_RAP_JITTER            float64
 72   STORY1IMM_PPQ5_JITTER           float64
 73   STORY1IMM_DDP_JITTER            float64
 74   STORY1IMM_LOCAL_SHIMMER         float64
 75   STORY1IMM_LOCAL_DB_SHIMMER      float64
 76   STORY1IMM_APQ3_SHIMMER          float64
 77   STORY1IMM_APQ5_SHIMMER          float64
 78   STORY1IMM_APQ11_SHIMMER         float64
 79   STORY2IMM_LANGUAGE              object
 80   STORY2IMM_PLAYBACK_COUNT        float64
 81   STORY2IMM_AUDIO_LENGTH          float64
 82   STORY2IMM_NUM_PRONOUNS          float64
 83   STORY2IMM_NUM_NOUNS             float64
 84   STORY2IMM_NUM_PROPER_NOUNS      float64
 85   STORY2IMM_NUM_VERBS             float64
 86   STORY2IMM_NUM_ADVERBS           float64
 87   STORY2IMM_NUM_ADJECTIVES        float64
 88   STORY2IMM_NUM_WORDS             float64
 89   STORY2IMM_IDEA_DENSITY          float64
 90   STORY2IMM_UNIQUE_WORDS_RATIO    float64
 91   STORY2IMM_MEAN_LETTER_PER_WORD  float64
 92   STORY2IMM_GMATCH                float64
 93   STORY2IMM_SPEECH_DURATION       float64
 94   STORY2IMM_NONSPEECH_PROPORTION  float64
 95   STORY2IMM_SPEECH_RATE           float64
 96   STORY2IMM_ARTICULATION_RATE     float64
 97   STORY2IMM_NUM_PAUSES            float64
 98   STORY2IMM_MEAN_PAUSE_LENGTH     float64
 99   STORY2IMM_AMPLITUDE_SD          float64
 100  STORY2IMM_F0_MEAN               float64
 101  STORY2IMM_F0_SD                 float64
 102  STORY2IMM_INTENSITY_MEAN        float64
 103  STORY2IMM_INTENSITY_SD          float64
 104  STORY2IMM_MFCC_1_MEAN           float64
 105  STORY2IMM_MFCC_2_MEAN           float64
 106  STORY2IMM_MFCC_3_MEAN           float64
 107  STORY2IMM_MFCC_4_MEAN           float64
 108  STORY2IMM_MFCC_5_MEAN           float64
 109  STORY2IMM_MFCC_6_MEAN           float64
 110  STORY2IMM_MFCC_7_MEAN           float64
 111  STORY2IMM_MFCC_8_MEAN           float64
 112  STORY2IMM_MFCC_9_MEAN           float64
 113  STORY2IMM_MFCC_10_MEAN          float64
 114  STORY2IMM_MFCC_11_MEAN          float64
 115  STORY2IMM_MFCC_12_MEAN          float64
 116  STORY2IMM_MFCC_13_MEAN          float64
 117  STORY2IMM_MFCC_1_SD             float64
 118  STORY2IMM_MFCC_2_SD             float64
 119  STORY2IMM_MFCC_3_SD             float64
 120  STORY2IMM_MFCC_4_SD             float64
 121  STORY2IMM_MFCC_5_SD             float64
 122  STORY2IMM_MFCC_6_SD             float64
 123  STORY2IMM_MFCC_7_SD             float64
 124  STORY2IMM_MFCC_8_SD             float64
 125  STORY2IMM_MFCC_9_SD             float64
 126  STORY2IMM_MFCC_10_SD            float64
 127  STORY2IMM_MFCC_11_SD            float64
 128  STORY2IMM_MFCC_12_SD            float64
 129  STORY2IMM_MFCC_13_SD            float64
 130  STORY2IMM_FORMANTS_1_MEAN       float64
 131  STORY2IMM_FORMANTS_2_MEAN       float64
 132  STORY2IMM_FORMANTS_3_MEAN       float64
 133  STORY2IMM_FORMANTS_4_MEAN       float64
 134  STORY2IMM_FORMANTS_1_SD         float64
 135  STORY2IMM_FORMANTS_2_SD         float64
 136  STORY2IMM_FORMANTS_3_SD         float64
 137  STORY2IMM_FORMANTS_4_SD         float64
 138  STORY2IMM_LOCAL_JITTER          float64
 139  STORY2IMM_LOCAL_ABS_JITTER      float64
 140  STORY2IMM_RAP_JITTER            float64
 141  STORY2IMM_PPQ5_JITTER           float64
 142  STORY2IMM_DDP_JITTER            float64
 143  STORY2IMM_LOCAL_SHIMMER         float64
 144  STORY2IMM_LOCAL_DB_SHIMMER      float64
 145  STORY2IMM_APQ3_SHIMMER          float64
 146  STORY2IMM_APQ5_SHIMMER          float64
 147  STORY2IMM_APQ11_SHIMMER         float64
 148  STORY1DEL_LANGUAGE              object
 149  STORY1DEL_PLAYBACK_COUNT        float64
 150  STORY1DEL_AUDIO_LENGTH          float64
 151  STORY1DEL_NUM_PRONOUNS          float64
 152  STORY1DEL_NUM_NOUNS             float64
 153  STORY1DEL_NUM_PROPER_NOUNS      float64
 154  STORY1DEL_NUM_VERBS             float64
 155  STORY1DEL_NUM_ADVERBS           float64
 156  STORY1DEL_NUM_ADJECTIVES        float64
 157  STORY1DEL_NUM_WORDS             float64
 158  STORY1DEL_IDEA_DENSITY          float64
 159  STORY1DEL_UNIQUE_WORDS_RATIO    float64
 160  STORY1DEL_MEAN_LETTER_PER_WORD  float64
 161  STORY1DEL_GMATCH                float64
 162  STORY1DEL_GMATCH_IMM_DEL        float64
 163  STORY1DEL_SPEECH_DURATION       float64
 164  STORY1DEL_NONSPEECH_PROPORTION  float64
 165  STORY1DEL_SPEECH_RATE           float64
 166  STORY1DEL_ARTICULATION_RATE     float64
 167  STORY1DEL_NUM_PAUSES            float64
 168  STORY1DEL_MEAN_PAUSE_LENGTH     float64
 169  STORY1DEL_AMPLITUDE_SD          float64
 170  STORY1DEL_F0_MEAN               float64
 171  STORY1DEL_F0_SD                 float64
 172  STORY1DEL_INTENSITY_MEAN        float64
 173  STORY1DEL_INTENSITY_SD          float64
 174  STORY1DEL_MFCC_1_MEAN           float64
 175  STORY1DEL_MFCC_2_MEAN           float64
 176  STORY1DEL_MFCC_3_MEAN           float64
 177  STORY1DEL_MFCC_4_MEAN           float64
 178  STORY1DEL_MFCC_5_MEAN           float64
 179  STORY1DEL_MFCC_6_MEAN           float64
 180  STORY1DEL_MFCC_7_MEAN           float64
 181  STORY1DEL_MFCC_8_MEAN           float64
 182  STORY1DEL_MFCC_9_MEAN           float64
 183  STORY1DEL_MFCC_10_MEAN          float64
 184  STORY1DEL_MFCC_11_MEAN          float64
 185  STORY1DEL_MFCC_12_MEAN          float64
 186  STORY1DEL_MFCC_13_MEAN          float64
 187  STORY1DEL_MFCC_1_SD             float64
 188  STORY1DEL_MFCC_2_SD             float64
 189  STORY1DEL_MFCC_3_SD             float64
 190  STORY1DEL_MFCC_4_SD             float64
 191  STORY1DEL_MFCC_5_SD             float64
 192  STORY1DEL_MFCC_6_SD             float64
 193  STORY1DEL_MFCC_7_SD             float64
 194  STORY1DEL_MFCC_8_SD             float64
 195  STORY1DEL_MFCC_9_SD             float64
 196  STORY1DEL_MFCC_10_SD            float64
 197  STORY1DEL_MFCC_11_SD            float64
 198  STORY1DEL_MFCC_12_SD            float64
 199  STORY1DEL_MFCC_13_SD            float64
 200  STORY1DEL_FORMANTS_1_MEAN       float64
 201  STORY1DEL_FORMANTS_2_MEAN       float64
 202  STORY1DEL_FORMANTS_3_MEAN       float64
 203  STORY1DEL_FORMANTS_4_MEAN       float64
 204  STORY1DEL_FORMANTS_1_SD         float64
 205  STORY1DEL_FORMANTS_2_SD         float64
 206  STORY1DEL_FORMANTS_3_SD         float64
 207  STORY1DEL_FORMANTS_4_SD         float64
 208  STORY1DEL_LOCAL_JITTER          float64
 209  STORY1DEL_LOCAL_ABS_JITTER      float64
 210  STORY1DEL_RAP_JITTER            float64
 211  STORY1DEL_PPQ5_JITTER           float64
 212  STORY1DEL_DDP_JITTER            float64
 213  STORY1DEL_LOCAL_SHIMMER         float64
 214  STORY1DEL_LOCAL_DB_SHIMMER      float64
 215  STORY1DEL_APQ3_SHIMMER          float64
 216  STORY1DEL_APQ5_SHIMMER          float64
 217  STORY1DEL_APQ11_SHIMMER         float64
 218  update_stamp                    object
dtypes: float64(205), int64(4), object(10)
memory usage: 17.5+ MB

In [37]:
parent_questionnaire_df.describe()

,RID,MOTHALIVE,MOTHAGE,MOTHDEM,MOTHAD,MOTHSXAGE,FATHALIVE,FATHAGE,FATHDEM,FATHAD,FATHSXAGE,ID,SITEID,HAS_QC_ERROR
count,2245.000000,2215.000000,2147.000000,2209.000000,943.000000,927.000000,2210.000000,2110.000000,2196.000000,440.000000,422.000000,2245.000000,2245.000000,1191.0
mean,7717.114477,0.168849,80.605030,0.488456,0.887593,76.248112,0.085973,75.346445,0.295082,0.813636,76.582938,59578.257461,85.701114,0.0
std,2087.973016,0.380682,13.327425,0.542553,0.600853,9.379158,0.299135,14.517982,0.543668,0.623602,8.917755,40363.587248,153.646457,0.0
min,21.000000,0.000000,17.000000,0.000000,0.000000,16.000000,0.000000,24.000000,0.000000,0.000000,45.000000,15.000000,1.000000,0.0
25%,6357.000000,0.000000,75.000000,0.000000,1.000000,70.000000,0.000000,67.000000,0.000000,0.000000,70.000000,28329.000000,21.000000,0.0
50%,6849.000000,0.000000,84.000000,0.000000,1.000000,77.000000,0.000000,79.000000,0.000000,1.000000,77.000000,52060.000000,37.000000,0.0
75%,10210.000000,0.000000,89.000000,1.000000,1.000000,83.000000,0.000000,86.000000,1.000000,1.000000,84.000000,83288.000000,67.000000,0.0
max,10854.000000,2.000000,105.000000,2.000000,2.000000,102.000000,2.000000,110.000000,2.000000,2.000000,99.000000,185322.000000,941.000000,0.0

In [36]:
parent_questionnaire_df.head()

,PHASE,PTID,RID,VISCODE,VISCODE2,VISDATE,MOTHALIVE,MOTHAGE,MOTHDEM,MOTHAD,...,FATHAD,FATHSXAGE,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
0,ADNI3,027_S_6001,6001,sc,sc,2016-12-13,0.0,88.0,NaN,NaN,...,NaN,NaN,95,20,2016-12-28,2016-12-28,NaN,NaN,NaN,2017-10-26 14:25:19.0
1,ADNI3,027_S_6002,6002,sc,sc,2017-01-03,0.0,49.0,0.0,NaN,...,NaN,NaN,223,20,2017-01-06,2017-01-06,NaN,NaN,NaN,2017-10-26 14:25:19.0
2,ADNI3,024_S_6004,6004,sc,sc,2017-02-14,0.0,94.0,0.0,NaN,...,1.0,80.0,685,19,2017-02-14,2017-02-14,NaN,NaN,NaN,2017-08-02 07:51:30.0
3,ADNI3,024_S_6005,6005,sc,sc,2017-02-22,0.0,94.0,0.0,NaN,...,1.0,84.0,975,19,2017-02-23,2017-02-23,NaN,NaN,NaN,2017-10-26 14:25:19.0
4,ADNI3,037_S_1078,1078,init,m120,2017-02-22,NaN,NaN,NaN,NaN,...,NaN,NaN,1335,27,2017-03-10,2017-03-10,NaN,NaN,NaN,2017-08-02 07:51:30.0

In [ ]:
parent_questionnaire_cols = ['FHQMOM', 'FHQMOMAD', 'FHQDAD', 'FHQDADAD']

In [40]:
# Join the parent questionnaire data with the main dataframe based on the 'RID' column
net_df = df.merge(parent_questionnaire_df, on='RID', how='left')
net_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17463 entries, 0 to 17462
Data columns (total 139 columns):
 #    Column                    Dtype
---   ------                    -----
 0    RID                       int64
 1    COLPROT                   object
 2    ORIGPROT                  object
 3    PTID_x                    object
 4    SITE                      int64
 5    VISCODE_x                 object
 6    EXAMDATE                  object
 7    DX_bl                     object
 8    AGE                       float64
 9    PTGENDER                  object
 10   PTEDUCAT                  int64
 11   PTETHCAT                  object
 12   PTRACCAT                  object
 13   PTMARRY                   object
 14   APOE4                     float64
 15   FDG                       float64
 16   PIB                       float64
 17   AV45                      float64
 18   FBB                       float64
 19   ABETA                     object
 20   TAU                       object
 21   PTAU                      object
 22   CDRSB                     float64
 23   ADAS11                    float64
 24   ADAS13                    float64
 25   ADASQ4                    float64
 26   MMSE                      float64
 27   RAVLT_immediate           float64
 28   RAVLT_learning            float64
 29   RAVLT_forgetting          float64
 30   RAVLT_perc_forgetting     float64
 31   LDELTOTAL                 float64
 32   DIGITSCOR                 float64
 33   TRABSCOR                  float64
 34   FAQ                       float64
 35   MOCA                      float64
 36   EcogPtMem                 float64
 37   EcogPtLang                float64
 38   EcogPtVisspat             float64
 39   EcogPtPlan                float64
 40   EcogPtOrgan               float64
 41   EcogPtDivatt              float64
 42   EcogPtTotal               float64
 43   EcogSPMem                 float64
 44   EcogSPLang                float64
 45   EcogSPVisspat             float64
 46   EcogSPPlan                float64
 47   EcogSPOrgan               float64
 48   EcogSPDivatt              float64
 49   EcogSPTotal               float64
 50   FLDSTRENG                 object
 51   FSVERSION                 object
 52   IMAGEUID                  float64
 53   Ventricles                float64
 54   Hippocampus               float64
 55   WholeBrain                float64
 56   Entorhinal                float64
 57   Fusiform                  float64
 58   MidTemp                   float64
 59   ICV                       float64
 60   DX                        object
 61   mPACCdigit                float64
 62   mPACCtrailsB              float64
 63   EXAMDATE_bl               object
 64   CDRSB_bl                  float64
 65   ADAS11_bl                 float64
 66   ADAS13_bl                 float64
 67   ADASQ4_bl                 float64
 68   MMSE_bl                   float64
 69   RAVLT_immediate_bl        float64
 70   RAVLT_learning_bl         float64
 71   RAVLT_forgetting_bl       float64
 72   RAVLT_perc_forgetting_bl  float64
 73   LDELTOTAL_BL              float64
 74   DIGITSCOR_bl              float64
 75   TRABSCOR_bl               float64
 76   FAQ_bl                    float64
 77   mPACCdigit_bl             float64
 78   mPACCtrailsB_bl           float64
 79   FLDSTRENG_bl              object
 80   FSVERSION_bl              object
 81   IMAGEUID_bl               float64
 82   Ventricles_bl             float64
 83   Hippocampus_bl            float64
 84   WholeBrain_bl             float64
 85   Entorhinal_bl             float64
 86   Fusiform_bl               float64
 87   MidTemp_bl                float64
 88   ICV_bl                    float64
 89   MOCA_bl                   float64
 90   EcogPtMem_bl              float64
 91   EcogPtLang_bl             float64
 92   EcogPtVisspat_bl          float64
 93   EcogPtPlan_bl             float64
 94   EcogPtOrgan_bl            float64
 95   EcogPtDivatt_bl           float64
 96   EcogPtTotal_bl            float64
 97   EcogSPMem_bl              float64
 98   EcogSPLang_bl             float64
 99   EcogSPVisspat_bl          float64
 100  EcogSPPlan_bl             float64
 101  EcogSPOrgan_bl            float64
 102  EcogSPDivatt_bl           float64
 103  EcogSPTotal_bl            float64
 104  ABETA_bl                  object
 105  TAU_bl                    object
 106  PTAU_bl                   object
 107  FDG_bl                    float64
 108  PIB_bl                    float64
 109  AV45_bl                   float64
 110  FBB_bl                    float64
 111  Years_bl                  float64
 112  Month_bl                  float64
 113  Month                     int64
 114  M                         int64
 115  update_stamp_x            object
 116  PHASE                     object
 117  PTID_y                    object
 118  VISCODE_y                 object
 119  VISCODE2                  object
 120  VISDATE                   object
 121  MOTHALIVE                 float64
 122  MOTHAGE                   float64
 123  MOTHDEM                   float64
 124  MOTHAD                    float64
 125  MOTHSXAGE                 float64
 126  FATHALIVE                 float64
 127  FATHAGE                   float64
 128  FATHDEM                   float64
 129  FATHAD                    float64
 130  FATHSXAGE                 float64
 131  ID                        float64
 132  SITEID                    float64
 133  USERDATE                  object
 134  USERDATE2                 object
 135  DD_CRF_VERSION_LABEL      object
 136  LANGUAGE_CODE             object
 137  HAS_QC_ERROR              float64
 138  update_stamp_y            object
dtypes: float64(101), int64(5), object(33)
memory usage: 18.5+ MB